### ISSUE TITLE
NUTS2 and NUTS3 map files don't exist

### ISSUE THREAD

**Issue by JohnKyne** [cran/csodata#1]
Both `cso_get_geo("NUTS2")` and  `cso_get_geo("NUTS3")` are bringing up errors stating the files doesn't exist. 

> trying URL 'https://opendata.arcgis.com/datasets/1a5d91a11ad9454d865ad426bbf5bc37_2.zip'
>Content type 'application/zip' length unknown
>downloaded 1.1 MB
>
>Error: Cannot open "C:\Users\x\AppData\Local\Temp\RtmpGUTLT1/NUTS3_Boundaries_Generalised_20m__OSi_National_Statistical_Boundaries__2015.shp"; The file doesn't seem to exist.

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the `DESCRIPTION` file. Thanks!

**Comment by Prockure** [comment]
Apologies, just fired this issue quickly without seeing that.

**Comment by JohnKyne** [comment]
Apologies, closing now and will email the author.
